import { Plus_Jakarta_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const plusJakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
	variable: "--font-plus-jakarta",
	weight: ["300", "400", "500", "600", "700", "800"],
});

const playfair = Playfair_Display({
	subsets: ["latin"],
	variable: "--font-playfair",
	weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
	title: "Inspo || Build Skills That Actually Matters",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${plusJakarta.variable} ${playfair.variable} antialiased`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
