import { Plus_Jakarta_Sans, Newsreader } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const plusJakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
	variable: "--font-plus-jakarta",
	weight: ["300", "400", "500", "600", "700", "800"],
});

const newsreader = Newsreader({
	subsets: ["latin"],
	variable: "--font-newsreader",
	weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${plusJakarta.variable} ${newsreader.variable} antialiased`}
			>
        <Navbar/>
				{children}
			</body>
		</html>
	);
}
